---
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56 # v0.15.20
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/adrienverge/yamllint.git
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530 # v1.38.0
    hooks:
      - id: yamllint

  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: a4d5d37e66ebcd6b3705204a1d6dbb56dea66338 # v0.49.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
