"""Top level: a host policy file -> a complete nftables ruleset string.

Resolves `- include:` in both `sets:` and `rules:` lists, applies the host's
per-site definition overlay (`site:`), builds each table's named-set registry,
and renders tables -> sets -> chains.
"""
from __future__ import annotations

import pathlib

import yaml

from nftgen.definitions import Definitions
from nftgen.ir import Table, build_sets
from nftgen.rules import RuleRenderer, build_chain


def _resolve_list(items: list, key: str, base_dir: pathlib.Path) -> list:
    """Flatten a list, expanding `{include: path}` entries (recursively).

    `key` is the section pulled from an include file ('sets' or 'rules').
    Nested includes resolve relative to the same base_dir.
    """
    out: list = []
    for item in items or []:
        if isinstance(item, dict) and "include" in item:
            data = yaml.safe_load((base_dir / item["include"]).read_text()) or {}
            out.extend(_resolve_list(data.get(key, []), key, base_dir))
        else:
            out.append(item)
    return out


def generate(
    policy_path: str | pathlib.Path,
    defs_dir: str | pathlib.Path,
    include_base: str | pathlib.Path,
    sites_dir: str | pathlib.Path | None = None,
) -> str:
    policy_path = pathlib.Path(policy_path)
    include_base = pathlib.Path(include_base)
    policy = yaml.safe_load(policy_path.read_text()) or {}

    site_files: list[pathlib.Path] = []
    if policy.get("site") and sites_dir:
        site_files = [pathlib.Path(sites_dir) / f"{policy['site']}.yaml"]
    defs = Definitions.load(defs_dir, site_files=site_files)

    tables = []
    for tspec in policy.get("tables", []):
        sets_spec = _resolve_list(tspec.get("sets", []), "sets", include_base)
        sets = build_sets(sets_spec, defs)
        counters = list(tspec.get("counters", []))
        renderer = RuleRenderer(defs, {s.name: s for s in sets}, counters=set(counters))

        chains = []
        for cspec in tspec.get("chains", []):
            cspec = dict(cspec)
            cspec["rules"] = _resolve_list(cspec.get("rules", []), "rules", include_base)
            chains.append(build_chain(cspec, renderer))

        tables.append(
            Table(
                family=tspec["family"],
                name=tspec["name"],
                sets=sets,
                chains=chains,
                raw=list(tspec.get("raw", [])),
                counters=counters,
            )
        )

    header = (
        "#!/usr/sbin/nft -f\n"
        f"# generated by nftgen from {policy_path.name} — do not edit\n"
    )
    return header + "\n" + "\n".join(t.render() for t in tables)
