"""Top level: a host policy file -> a complete nftables ruleset string.

Resolves `- include:` in both `sets:` and `rules:` lists, applies the host's
per-site definition overlay (`site:`), builds each table's named-set registry,
and renders tables -> sets -> chains.
"""
from __future__ import annotations

import pathlib

import yaml

from nftgen.definitions import Definitions
from nftgen.ir import Table, build_sets
from nftgen.rules import RuleRenderer, build_chain, build_flowtables


def _resolve_list(items: list, key: str, base_dir: pathlib.Path) -> list:
    """Flatten a list, expanding `{include: path}` entries (recursively).

    `key` is the section pulled from an include file ('sets' or 'rules').
    Nested includes resolve relative to the same base_dir.
    """
    out: list = []
    for item in items or []:
        if isinstance(item, dict) and "include" in item:
            data = yaml.safe_load((base_dir / item["include"]).read_text()) or {}
            out.extend(_resolve_list(data.get(key, []), key, base_dir))
        else:
            out.append(item)
    return out


def generate(
    policy_path: str | pathlib.Path,
    defs_dir: str | pathlib.Path,
    include_base: str | pathlib.Path,
    sites_dir: str | pathlib.Path | None = None,
    flush: bool = False,
) -> str:
    policy_path = pathlib.Path(policy_path)
    include_base = pathlib.Path(include_base)
    policy = yaml.safe_load(policy_path.read_text()) or {}

    site_files: list[pathlib.Path] = []
    if policy.get("site") and sites_dir:
        site_files = [pathlib.Path(sites_dir) / f"{policy['site']}.yaml"]
    defs = Definitions.load(defs_dir, site_files=site_files)

    tables = []
    for tspec in policy.get("tables", []):
        sets_spec = _resolve_list(tspec.get("sets", []), "sets", include_base)
        sets = build_sets(sets_spec, defs)
        counters = list(tspec.get("counters", []))
        renderer = RuleRenderer(defs, {s.name: s for s in sets}, counters=set(counters))

        chains = []
        for cspec in tspec.get("chains", []):
            cspec = dict(cspec)
            cspec["rules"] = _resolve_list(cspec.get("rules", []), "rules", include_base)
            chains.append(build_chain(cspec, renderer))

        tables.append(
            Table(
                family=tspec["family"],
                name=tspec["name"],
                sets=sets,
                chains=chains,
                raw=list(tspec.get("raw", [])),
                counters=counters,
                flowtables=build_flowtables(tspec.get("flowtables", []), defs),
            )
        )

    header = (
        "#!/usr/sbin/nft -f\n"
        f"# generated by nftgen from {policy_path.name} — do not edit\n"
    )
    # `flush ruleset` makes the file a complete, atomic, reapply-safe deploy
    # artifact (the build() output that ships verbatim as /etc/nftables.conf).
    # generate() stays flush-free for composition/embedding (DECISIONS §5.3).
    flush_prefix = "flush ruleset\n\n" if flush else ""
    return header + "\n" + flush_prefix + "\n".join(t.render() for t in tables)


def build(
    root: str | pathlib.Path, host: str | None = None
) -> dict[str, str]:
    """Generate the deploy `.nft` for every host under ``<root>`` (or just ``host``).

    Convention layout: ``<root>/{def, sites, policies/includes, policies/hosts}``.
    Returns ``{host_name: text}`` where each text is a complete, applyable ruleset
    (with ``flush ruleset``). The host name is the policy filename stem — the
    ``inventory_hostname == policies/hosts/<name>.yaml == generated/<name>.nft``
    contract (DEPLOYMENT §10.2).
    """
    root = pathlib.Path(root)
    defs_dir = root / "def"
    include_base = root / "policies"
    sites_dir = root / "sites"
    hosts_dir = root / "policies" / "hosts"

    if host is not None:
        host_files = sorted(hosts_dir.glob(f"{host}.y*ml"))
        if not host_files:
            raise FileNotFoundError(f"no host policy {host!r} under {hosts_dir}")
    else:
        host_files = sorted(hosts_dir.glob("*.y*ml"))

    return {
        hf.stem: generate(hf, defs_dir, include_base, sites_dir, flush=True)
        for hf in host_files
    }
